#!/bin/bash

echo $BASH_VERSION
VAL_ACCURACY=0
BEST=0

touch runs/$1/best

for LR in 0.005 0.001 0.0005 0.0001
do
    for BS in 20 60 120
    do
        for HS in 32 64 128 256
        do
            SEED=$RANDOM
            EXPERIMENT="${OPT}_LR_${LR}_BS_${BS}_HS_${HS}"
            echo "python train_dgn.py lr: ${LR} hidden_size: ${HS} batch_size: ${BS} seed: ${SEED}"
            python train_dgn.py $1 $EXPERIMENT $LR $HS $BS 0.1 100 $SEED

            VAL_ACCURACY=`cat runs/$1/$EXPERIMENT/best_result.json | python3 -c "import sys, json; print(json.load(sys.stdin)['val_acc'])"`

            echo $VAL_ACCURACY
            if echo $VAL_ACCURACY $BEST | awk '{exit !( $1 > $2)}'; then
                echo "NEW BEST"
                BEST=$VAL_ACCURACY
                echo $EXPERIMENT > runs/$1/best
            fi

            echo "--------------------DONE------------------------"
        done
    done
done
